apiKey = "Sj16b2MdofYWWBOGkvlng4NRVCG9gEdvLyOytTJscQz2feHfvYZUiFIkCpwDtTtZ"
secretKey = "Tjw2dNO5zt7k8GHGyhLzAHwFlhLRxiKusMqy7SkMWiLRTXlXx9Oc0WmCncmChApb"
interval = "Client.KLINE_INTERVAL_1MINUTE"
start_time = "3 November, 2023"
end_time = "4 November, 2023"
